### ISSUE TITLE
Make use of enhanced ecommerce context

### ISSUE THREAD

**Issue by awoehrl** [snowplow/dbt-snowplow-ecommerce#26]
## Is your feature request related to a problem? Please describe.
The Snowplow GTM template encourages us (https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/google-tag-manager-custom-template/template-for-javascript-tracker-v3/tag-template-guide/#caveats)  to use enhanced ecommerce, but the dbt ecommerce models don't seem to use the EEC fields.

## Describe the solution you'd like
It would be great, if dbt-snowplow-ecommerce would work with the eec events.

**Comment by rlh1994** [comment]
Hi @awoehrl , we're actually planning to mark the old e-commerce and enhanced e-commerce as deprecated in the v4 of the JS tracker, so it's not likely that we'll develop this package to support those. We do however have a how-to planned on our roadmap for implementing the Snowplow e-commerce with GTM, although it won't be via a new tag. Once that's ready we'll get the docs updated.

**Comment by awoehrl** [comment]
I understand, thank you!
