### ISSUE TITLE
Add list_click to product_interactions

### ISSUE THREAD

**Issue by awoehrl** [snowplow/dbt-snowplow-ecommerce#39]
Hi!

It feels like an oversight, that the `list_click` snowplow_ecommerce_action is not part of the product_interactions table. Is this intentional?

Cheers
Andreas

**Comment by rlh1994** [comment]
@awoehrl I'll check with the team, it may be this was added later to the tracking and so wasn't available when we first built the package, or there may be some other reason I am not aware of it was excluded. We're planning to do some work on this package soon so will look at including this when we do that work if appropriate.

**Comment by awoehrl** [comment]
Thank you!
